version: 2

sources:
  - name: main
    tables:
      - name: trip_punctuality
      - name: gtfs_routes
      - name: gtfs_trips

models:
  - name: stg_trip_punctuality
    columns:
      - name: route_id
        tests:
          - not_null
      - name: delay_sec
        tests:
          - not_null