name: Collect bus data

on:
  schedule: # 7 - 19 nz time
    - cron: "*/10 19-23 * * *"   # UTC 19:00-23:59
    - cron: "*/10 0-7 * * *"     # UTC 00:00-07:59
  workflow_dispatch:

jobs:
  collect:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: pip install -r requirements.txt
      - run: python pipeline.py
        env:
          SUPABASE_DB_URL: ${{ secrets.SUPABASE_DB_URL }}
          AT_SUB_KEY: ${{ secrets.AT_SUB_KEY }}